http:
  serversTransports:
    minio-api:
      serverName: minio-api.day1.sololab
      rootcas:
        - "/etc/traefik/tls/ca.crt"
    minio-console:
      serverName: minio-console.day1.sololab
      rootcas:
        - "/etc/traefik/tls/ca.crt"
