hyperv_user     = "root"
hyperv_password = "P@ssw0rd"
vm_name         = "SvcDisc-FCOS"
source_disk     = "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks\\Images\\Virtual Hard Disks\\fedora-coreos-38.20231027.3.2-hyperv.x86_64.vhdx"
data_disk_path  = "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks\\Data_Disk\\SvcDisc-FCOS-Data.vhdx"
