ARG EE_BASE_IMAGE=quay.io/ansible/ansible-runner:latest
ARG EE_BUILDER_IMAGE=quay.io/ansible/ansible-builder:latest

FROM $EE_BASE_IMAGE as galaxy
ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=-v
ARG PROXY
USER root

ADD _build /build
WORKDIR /build

# https://groups.google.com/g/ansible-project/c/L2H6KSAF_o0
RUN git config --global http.proxy $PROXY && \
    git config --global https.proxy $PROXY && \
    ansible-galaxy role install -r requirements.yml --roles-path "/usr/share/ansible/roles" && \
    git config --global --unset http.proxy && \
    git config --global --unset https.proxy
RUN export HTTPS_PROXY=${PROXY} HTTP_PROXY=${PROXY} && \
    ANSIBLE_GALAXY_DISABLE_GPG_VERIFY=1 ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path "/usr/share/ansible/collections" && \
    unset HTTPS_PROXY && \
    unset HTTP_PROXY

FROM $EE_BUILDER_IMAGE as builder

COPY --from=galaxy /usr/share/ansible /usr/share/ansible

ADD _build/requirements.txt requirements.txt
ADD _build/bindep.txt bindep.txt
RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
RUN assemble

FROM $EE_BASE_IMAGE
ARG PROXY
USER root

COPY --from=galaxy /usr/share/ansible /usr/share/ansible

COPY --from=builder /output/ /output/
RUN /output/install-from-bindep && rm -rf /output/wheels
# https://github.com/lshake/ee_shakeytowers2/blob/c8886455e01774b34a22096452d266723250ef7c/shakeytowers/ee.yml
# https://docs.openshift.com/container-platform/4.11/applications/working_with_helm_charts/installing-helm.html
RUN export HTTPS_PROXY=${PROXY} && \
    export HTTP_PROXY=${PROXY} && \
    curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && \
    ls -al /usr/local/bin/kubectl && \
    chmod 0755 /usr/local/bin/kubectl && \
    curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm && \
    chmod +x /usr/local/bin/helm && \
    git config --global http.proxy $PROXY && \
    git config --global https.proxy $PROXY && \
    /usr/local/bin/helm plugin install https://github.com/databus23/helm-diff && \
    git config --global --unset http.proxy && \
    git config --global --unset https.proxy && \
    unset HTTPS_PROXY && \
    unset HTTP_PROXY && \
    unset https_proxy && \
    unset http_proxy