http:
  middlewares:
    toHttps:
      redirectScheme:
        scheme: https
        permanent: true
    userPass:
      basicAuth:
        users:
          - admin:$apr1$/F5ai.wT$7nFJWh4F7ZA0qoY.JZ69l1
  # routers:
  #   dashboard-redirect:
  #     entryPoints:
  #       - web
  #     middlewares:
  #       - toHttps@file
  #       - userPass@file
  #     rule: Host(`traefik.day1.sololab`) && (PathPrefix(`/api`)|| PathPrefix(`/dashboard`))
  #     service: api@internal
  #   dashboard:
  #     entryPoints:
  #       - webSecure
  #     middlewares:
  #       - userPass@file
  #     rule: Host(`traefik.day1.sololab`) && (PathPrefix(`/api`)|| PathPrefix(`/dashboard`))
  #     service: api@internal
  #     tls:
  #       certresolver: internal
# tls:
#   certificates:
#     - certFile: /etc/traefik/tls/day0.crt
#       keyFile: /etc/traefik/tls/day0.key
