global:
  imageRegistry: zot.day0.sololab
alloy:
  containerPorts: []
  config:
    - component: loki.source.journal
      label: journal
      attributes:

  podLabels:
    traefik.enable: true
    traefik.http.routers.alloy-redirect.entrypoints: web
    traefik.http.routers.alloy-redirect.rule: Host(`alloy.day1.sololab`)
    traefik.http.routers.alloy-redirect.middlewares: toHttps@file
    traefik.http.routers.alloy.entryPoints: webSecure
    traefik.http.routers.alloy.rule: Host(`alloy.day1.sololab`)
    traefik.http.routers.alloy.tls.certresolver: internal
    traefik.http.services.alloy.loadbalancer.server.port: 3100
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
