# yaml-language-server: $schema=https://raw.githubusercontent.com/Relativ-IT/Butane-Schemas/Release/Butane-Schema.json
variant: fcos
version: 1.5.0
storage:
  files:
    - path: /etc/hostname
      contents:
        inline: ${vm_name}
    # https://github.com/coreos/coreos-tutorials/blob/97376716dce47080dd9e8f016753c55c5c79da96/fedora-coreos/provisioning/fcos-lab-tutorial.bu#L48
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 40-disable-passwords.conf.
          PasswordAuthentication yes
    # low down the unprivilege port
    - path: /etc/sysctl.d/90-unprivileged_port_start.conf
      contents:
        inline: |
          net.ipv4.ip_unprivileged_port_start = 53
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/${timezone}
