name: Terraform Job
run-name: ${{ gitea.actor }} is running Terraform

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: Directory containing the IaC
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      # - name: Install Terraform
      #   run: |
      #     wget https://releases.hashicorp.com/terraform/${{ matrix.terraform_version }}/terraform_${{ matrix.terraform_version }}_linux_amd64.zip
      #     unzip terraform_${{ matrix.terraform_version }}_linux_amd64.zip
      #     mv terraform /usr/local/bin/
      #     terraform version
      #   timeout-minutes: 5
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v4
        with:
          url: https://vault.day1.sololab
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportToken: true
          secrets: |
            kvv2_consul/data/token-tf_backend | CONSUL_HTTP_TOKEN ;
            kvv2_nomad/data/token-management | NOMAD_TOKEN ;

      - name: run terraform
        env:
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/TerraformWorkShop/SoloLab.tfrc
          CONSUL_HTTP_TOKEN: ${{ secrets.import-secrets.outputs.CONSUL_HTTP_TOKEN }}
          NOMAD_TOKEN: ${{ secrets.import-secrets.outputs.NOMAD_TOKEN }}
        run: |
          cd ${{ github.workspace }}/${{ inputs.working-directory }}
          terraform init
          terraform plan
