global:
  imageRegistry: zot.day0.sololab
opendj:
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_CONTAINER/POD%%
  ## @param opendj.setupProperties properties config when opendj setup
  ## aka environment variable for the opendj image
  ## ref: https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-packages/opendj-docker/README.md
  ##
  setupProperties:
    ## @param opendj.setupProperties.BASE_DN OpenDJ Base DN
    ##
    BASE_DN: dc=root,dc=sololab
    ## @param opendj.setupProperties.ROOT_PASSWORD Initial root user password
    ##
    ROOT_PASSWORD: P@ssw0rd
    ## @param opendj.setupProperties.OPENDJ_SSL_OPTIONS you can replace ssl options at here,
    ## like : "--usePkcs12keyStore /opt/domain.pfx --keyStorePassword domain"
    ##
    OPENDJ_SSL_OPTIONS: "--usePkcs12keyStore /opt/opendj/certs/keystore.p12 --keyStorePassword changeit"
  ssl:
    mountPath: /opt/opendj/certs
  ## @param opendj.podAnnotations Annotations for opendj pods
  ## to keep container user as same permission as host user, set keep-id point to the container user and group id
  ## the userns annotation only work podman v4.9+
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## ref: https://github.com/containers/podman/discussions/22378
  ## ref: https://github.com/OpenIdentityPlatform/OpenDJ/blob/4.9.1/opendj-packages/opendj-docker/Dockerfile#L31
  ##
  podAnnotations:
    io.podman.annotations.userns: keep-id:uid=1001,gid=1000
