# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
jenkins:
  authorizationStrategy:
    # loggedInUsersCanDoAnything:
    #   allowAnonymousRead: false
    # for role-strategy plugin, work together with oic plugin for role based access control
    roleBased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "Overall/Administer"
            entries:
              - group: "app-jenkins-admin"
          - name: "agent"
            permissions:
              - "Overall/Read"
              - "Agent/Build"
              - "Agent/Configure"
              - "Agent/Connect"
              - "Agent/Create"
              - "Agent/Delete"
              - "Agent/Disconnect"
              - "Agent/Provision"
            entries:
              - group: "app-jenkins-agent"
          - name: "read"
            permissions:
              - "View/Read"
            entries:
              - group: "app-jenkins-user"
  # https://github.com/jenkinsci/configuration-as-code-plugin/issues/2767
  # https://github.com/jenkins-infra/jenkins.io/issues/9060
  # crumbIssuer:
  #   standard:
  #     excludeClientIPFromCrumb: true
  securityRealm:
    # local:
    #   allowsSignup: false
    #   enableCaptcha: false
    #   users:
    #     - id: admin
    #       name: Jenkins Admin
    #       password: P@ssw0rd
    # https://github.com/jenkinsci/oic-auth-plugin/blob/master/docs/configuration/README.md
    # for oic-auth plugin
    oic:
      allowTokenAccessWithoutOicSession: true
      # Automatic config of endpoint
      serverConfiguration:
        wellKnown:
          wellKnownOpenIDConfigurationUrl: '{{with secret "kvv2_vault/data/oidc-provider_sololab"}}{{.Data.data.config_url}}{{end}}'
          scopesOverride: openid groups user
      # Credentials
      clientId: '{{with secret "kvv2_vault/data/oidc-client_jenkins"}}{{.Data.data.client_id}}{{end}}'
      clientSecret: '{{with secret "kvv2_vault/data/oidc-client_jenkins"}}{{.Data.data.client_secret}}{{end}}'
      # claims
      # uid configured in vault oidc provider, see TerraformWorkShop/Vault/Identity/OIDC/terraform.tfvars
      userNameField: uid
      fullNameFieldName: username
      groupsFieldName: groups
      emailFieldName: email
      userIdStrategy: caseSensitive
      groupIdStrategy: caseSensitive
      # Security
      disableSslVerification: true
      properties:
        - escapeHatch:
            username: admin
            secret: P@ssw0rd
            group: app-jenkins-admin
  slaveAgentPort: 50000

appearance:
  # for dark theme plugin
  themeManager:
    disableUserThemes: true
    theme: "darkSystem"

security:
  # for csp plugin
  contentSecurityPolicy:
    enforce: true

unclassified:
  hashicorpVault:
    configuration:
      vaultCredentialId: "vault"
      vaultUrl: "https://vault.day0.sololab"

  location:
    adminAddress: null
    url: "https://jenkins.day3.sololab"
  # https://www.jenkins.io/doc/book/security/user-content/#resource-root-url
  # https://www.jenkins.io/doc/book/security/configuring-content-security-policy/
  # https://www.jenkins.io/doc/book/security/csp/
  # in order to allow jenkins web origin site script run(for oidc login), we need to set resourceRoot to jenkins url
  resourceRoot:
    url: "https://jenkins.day3.sololab/"

credentials:
  system:
    domainCredentials:
      - credentials:
          - VaultAppRoleCredential:
              description: "Vault secret reader app role credential"
              id: "vault"
              scope: GLOBAL
              roleId: '{{with secret "kvv2_vault/data/approle-jenkins_secret_reader"}}{{.Data.data.role_id}}{{end}}'
              secretId: '{{with secret "kvv2_vault/data/approle-jenkins_secret_reader"}}{{.Data.data.secret_id}}{{end}}'
          - vaultUsernamePasswordCredentialImpl:
              engineVersion: 2
              id: "git-repo-operator"
              passwordKey: "password"
              path: "kvv2_others/git-repo-operator"
              scope: GLOBAL
              usernameKey: "username"
jobs:
  - script: >
      job('jobdsl_test') {
        steps {
            shell('whoami')
        }
      }
