resource_group_name_regex = "^DevOps-Root"
vpc_name_regex            = "^DevOps-VPC_HK$"
vswitch_name_regex        = "^DevOps-VSw_HKB1_Sub$"

nas_fs_desc           = "DevOps-NAS_HKB1"
nas_fs_type           = "standard"
nas_fs_storage_type   = "Performance"
nas_fs_protocol_type  = "NFS"
nas_ag_name           = "DevOps-NASAG_HK_RW"
nas_ar_rw_access_type = "RDWR"
