http:
  middlewares:
    toHttps:
      redirectScheme:
        scheme: https
        permanent: true
  serversTransports:
    zot:
      serverName: zot.day0.sololab
      rootcas:
        - "/etc/traefik/tls/ca.crt"
tls:
  certificates:
    - certFile: /etc/traefik/tls/day0.crt
      keyFile: /etc/traefik/tls/day0.key
