host        = "127.0.0.1"
user        = "root"
password    = "P@ssw0rd"
vm_name     = "InfraSvc-OpenSUSE_Leap"
source_disk = "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks\\output-opensuse-leap-15.5-base\\Virtual Hard Disks\\packer-opensuse-leap-g2.vhdx"
data_disk_ref = "../Disk-InfraSvc-OpenSUSE_Leap-Data/terraform.tfstate"