# https://www.runatlantis.io/docs/server-configuration.html
atlantis-url: https://atlantis.day4.sololab:443

locking-db-type: redis
redis-username: atlantis
redis-password: atlantis
redis-host: day3.redis.service.consul
redis-port: 6379
redis-db: 1

gitea-base-url: https://gitea.day4.sololab
gitea-token: {{ with secret "kvv2_others/data/app-atlantis" }}{{ .Data.data.gitea_token }}{{ end }}
gitea-user: {{ with secret "kvv2_others/data/app-atlantis" }}{{ .Data.data.gitea_user }}{{ end }}
gitea-webhook-secret: {{ with secret "kvv2_others/data/app-atlantis" }}{{ .Data.data.gitea_webhook_secret }}{{ end }}
repo-allowlist: 'gitea.day4.sololab/standalone-lab/*'

repo-config: /local/repos.yaml

# https://github.com/runatlantis/atlantis/pull/4494
# if use private tf download url, need to prepare a structure like releases.hashicorp.com, which include index.json,
#  let atlantis fetch the terraform bin version list and related download link, also need to provide the signature file for the package
# tf-download-url: