global:
  imageRegistry: zot.day0.sololab
nomad:
  image:
    repository: multani/nomad
  # https://github.com/containers/podman/discussions/23322#discussioncomment-12340550
  # hostAliases:
  #   - ip: "host-gateway"
  #     hostnames:
  #       - "vault.day0.sololab"
  containerPorts: []
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 300
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - nomad
        - server
        - members
        - -tls-skip-verify
        - -address
        - https://localhost:4646
  configFiles:
    main:
      acl:
        enabled: true
      tls:
        http: true
        rpc: true
        ca_file: "/nomad/config/certs/ca.crt"
        cert_file: "/nomad/config/certs/server.crt"
        key_file: "/nomad/config/certs/server.key"
      consul:
        address: "https://consul.day0.sololab:8501"
        ca_file: "/nomad/config/certs/ca.crt"
        ssl: true
        token: # set by vault data

  args:
    - agent

  podLabels:
    traefik.enable: true
    traefik.tcp.routers.nomad-web.entrypoints: webSecure
    traefik.tcp.routers.nomad-web.rule: HostSNI(`nomad.day0.sololab`)
    traefik.tcp.routers.nomad-web.tls.passthrough: true
    traefik.tcp.routers.nomad-web.service: nomad-web
    traefik.tcp.services.nomad-web.loadbalancer.server.port: 4646

  extraEnvVars:
    - name: NOMAD_DISABLE_PERM_MGMT
      value: "ture"
    # env var for image multani/nomad
    # https://github.com/multani/docker-nomad/blob/9f5cc384481214f0232b38262b0512c2d22a0887/v1.9.x/start.sh#L15
    - name: NOMAD_CONFIG_DIR
      value: /nomad/config
    - name: TZ
      value: Asia/Shanghai
    - name: NOMAD_ADDR
      value: https://nomad.day0.sololab:4646
    - name: NOMAD_CACERT
      value: /nomad/config/certs/ca.crt
