http:
  middlewares:
    # toHttps middleware already configured in traefik helm config map
    # toHttps:
    #   redirectScheme:
    #     scheme: https
    #     permanent: true
    userPass:
      basicAuth:
        users:
          - admin:$apr1$/F5ai.wT$7nFJWh4F7ZA0qoY.JZ69l1
tls:
  certificates:
    - certFile: /etc/traefik/tls/day0.crt
      keyFile: /etc/traefik/tls/day0.key
