## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: "zot.day0.sololab"

vault:
  containerPorts: []
  ## @param vault.configFiles config file to start vault, the sub config block will convert to json and injected as ConfigMap
  ## You can add whatever sub items under this block
  ## ref: https://developer.hashicorp.com/vault/docs/configuration
  ## ref: https://developer.hashicorp.com/vault/tutorials/operations/configure-vault#config
  ##
  configFiles:
    main:
      api_addr: "https://vault.day0.sololab:8200"
      cluster_addr: "https://vault.day0.sololab:8201"
      storage:
        raft:
          path: /vault/file
          node_id: raft_node_1
        file: null
      listener:
        - tcp:
            tls_disable: false
            address: "[::]:8200"
            cluster_address: "[::]:8201"
            # https://github.com/hashicorp/vault/blob/2718994242f94df3dc90215b2ecbc5d4198d9e3c/website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx#L191
            tls_cert_file: /vault/userconfig/vault-server-tls/tls.crt
            tls_key_file: /vault/userconfig/vault-server-tls/tls.key
            tls_client_ca_file: /vault/userconfig/vault-server-tls/ca.crt
            tls_disable_client_certs: true

  ## @param vault.podAnnotations Annotations for %%MAIN_CONTAINER_NAME%% pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## ref: https://github.com/containers/podman/discussions/22378
  ##
  podAnnotations:
    io.podman.annotations.userns: keep-id:uid=100,gid=1000

  podLabels:
    traefik.enable: true
    traefik.tcp.routers.vault-web.entrypoints: webSecure
    traefik.tcp.routers.vault-web.rule: HostSNI(`vault.day0.sololab`)
    traefik.tcp.routers.vault-web.tls.passthrough: true
    traefik.tcp.routers.vault-web.service: vault-web
    traefik.tcp.services.vault-web.loadbalancer.server.port: 8200

  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
    - name: SKIP_CHOWN
      value: "true"
    - name: SKIP_SETCAP
      value: "true"
    - name: VAULT_ADDR
      value: https://127.0.0.1:8200
    - name: VAULT_CACERT
      value: /vault/userconfig/vault-server-tls/ca.crt

  autoUnseal:
    enabled: true
    env:
      - name: VAULT_ADDR
        value: https://127.0.0.1:8200
      - name: VAULT_OPERATOR_SECRETS_JSON_PATH
        value: "/vault/unseal/vault_operator_secrets_b64"
      - name: SECRET_SHARES
        value: 5
      - name: SECRET_THRESHOLD
        value: 3

volumePermissions:
  enabled: true
  image:
    registry: zot.day0.sololab
    repository: hashicorp/vault
    tag: 1.19
