host          = "127.0.0.1"
user          = "root"
password      = "P@ssw0rd"
vm_name       = "Dev-Fedora"
source_disk   = "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks\\output-fedora38-base\\Virtual Hard Disks\\packer-fedora38-g2.vhdx"
data_disk_ref = "../Disk-Dev-Fedora-Data/terraform.tfstate"
