hyperv_user     = "root"
hyperv_password = "P@ssw0rd"
vm_name         = "CI-FCOS"
source_disk     = "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks\\Images\\Virtual Hard Disks\\fedora-coreos-39.20231204.3.3-hyperv.x86_64.vhdx"
fcos_timezone   = "Asia/Shanghai"
