host          = "127.0.0.1"
user          = "root"
password      = "P@ssw0rd"
vm_name       = "VyOS-LTS-133"
source_disk   = "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks\\Images\\Virtual Hard Disks\\packer-vyos133.vhdx"
data_disk_ref = "../Disk-Infra-VyOS-Data/terraform.tfstate"
