coredns:
  image:
    registry: zot.day0.sololab
    repository: coredns/coredns
    tag: 1.11.1
  containerPorts:
    - name: dns_tcp
      containerPort: 53
      hostPort: 53
      hostIP: "{{ .Values.coredns.hostIP }}"
      protocol: TCP
    - name: dns_udp
      containerPort: 53
      hostPort: 53
      hostIP: "{{ .Values.coredns.hostIP }}"
      protocol: UDP
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  servers:
    - zones:
        - zone: .
      port: 53
      plugins:
        - name: errors
        # Serves a /health endpoint on :8080, required for livenessProbe
        - name: health
          configBlock: |-
            lameduck 5s
        - name: forward
          parameters: . /etc/resolv.conf
        - name: cache
          parameters: 30
        # The loop plugin will send a random probe query to ourselves and will then keep track of how many times we see it.
        # If we see it more than twice, we assume CoreDNS has seen a forwarding loop and we halt the process.
        - name: loop
        - name: log
        # This plugin allows automatic reload of a changed Corefile.
        # To enable automatic reloading of zone file changes, use the auto plugin.
        - name: reload
        - name: file
          parameters: /etc/coredns/day0.sololab.db day0.sololab
  zoneFiles:
    - filename: day0.sololab.db
      domain: day0.sololab
      contents: |
        day0.sololab.   IN SOA ns.day0.sololab. admin.james.sololab. 2024061341 7200 3600 1209600 3600
        day0.sololab.   IN NS  ns1.day0.sololab.
        *.day0.sololab. IN A  {{ .Values.coredns.hostIP }}
